# Numpy - Manipulação de dados

In [1]:
import numpy as np

In [2]:
# Vetor de 1 dimensão
t1 = np.ones(4) # vetor com 4 elementos "1"
t1

array([1., 1., 1., 1.])

In [3]:
# Dimensões
t1.shape

(4,)

In [4]:
# Matriz 3D
t2 = np.ones((4, 3, 2)) # 4 matriz de 3 linhas 2 duas colunas cada

In [6]:
t2

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [7]:
t2.shape

(4, 3, 2)

In [8]:
# Matriz 3D com números aleatórios
t3 = np.random.random((4, 3, 2))
t3

array([[[0.71324171, 0.462591  ],
        [0.76476755, 0.28196772],
        [0.41201416, 0.78972063]],

       [[0.13067509, 0.3861955 ],
        [0.4827478 , 0.42879993],
        [0.64504674, 0.32353447]],

       [[0.65088785, 0.90445167],
        [0.554362  , 0.45875162],
        [0.63280461, 0.7198714 ]],

       [[0.34545349, 0.38248578],
        [0.45648471, 0.35835788],
        [0.7619696 , 0.09748253]]])

In [9]:
# Vetor com valores pré definidos
v1 = np.array([1,2,3,4])
v1

array([1, 2, 3, 4])

In [11]:
v2 = np.array([[1,2,3,4], [6,7,8,9]])
v2

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [12]:
v2.shape

(2, 4)

In [13]:
# Tamanho da estrutura de dados (número de elementos)
v2.size

8

In [14]:
# Número de dimensões
v2.ndim

2

In [16]:
# Tipo dos dados
v2.dtype

dtype('int64')

In [18]:
# Somar todos os valores
v2.sum()

40

In [20]:
# Valor máximo
v2.max()

9

In [21]:
# Valor mínimo
v2.min()

1

 Como acessar elementos dentro de array

In [25]:
v2

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [26]:
# Acessar primeiro elemento
v2[0,0] # linha 0, elemento 0

1

In [27]:
# Acessar segunda linha e terceiro elemento
v2[1,2]

8

In [28]:
# Acessar múltiplos elementos (primeira linha e segundo e terceiro elemento)
v2[0, 1:3] # 3 é exclusive (inclusive:exclusive)

array([2, 3])

Operações aritméticas

In [31]:
a = np.array([[1,2], [4,5]])
b = np.array([[10,20], [30,40]])

print(a)
print(b)

[[1 2]
 [4 5]]
[[10 20]
 [30 40]]


In [32]:
# Multiplicação (element-wise)
2 * a

array([[ 2,  4],
       [ 8, 10]])

In [33]:
# Soma
2 + a

array([[3, 4],
       [6, 7]])

In [34]:
# Multiplicação matricial
a.dot(b)

array([[ 70, 100],
       [190, 280]])

Exercício

In [36]:
# 1 Operações vetorizadas são extremamente mais eficientes do que a utilização de
# loops para realização de tais operações Faça um teste para provar a eficiência da
# biblioteca em relação ao uso de listas nativas do Python Crie dois vetores com
# 100000 elementos e faça um dot product Dica use a função time process_time do
# pacote ‘ para salvar o tempo antes e depois da operação O tempo decorrido
# em segundos pode ser calculado com a diferença entre estes valores

from time import process_time

In [37]:
# Criar lista
lista = [1] * 100000

In [39]:
len(lista)

100000

In [40]:
# Operação não vetorizada
tic = process_time()

# Inicializar variável que vai armazenar o resultado da multiplicação
dot = 0

for i in range(len(lista)):
  dot += lista[i] * lista[i]

toc = process_time()

toc - tic

0.021917580000000214

In [41]:
dot

100000

In [42]:
# Fazer operação vetorizada
a = np.asarray(lista)

tic = process_time()
dot = a.dot(a)
toc = process_time()

toc - tic

0.0007820300000016545

In [43]:
dot

100000

In [44]:
# Exercício 2: Demonstrativo financeiro de empresa

receitas = np.array([ 7606.46, 18611.41, 19175.41, 8758.65, 8105.44, 11496.28, 9766.09, 10305.32, 18379.96, 10713.97, 15433.50])
custos = np.array([ 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96])

In [47]:
# Calcular o lucro mensal
lucro = receitas - custos
lucro

array([ 1911.39,  6292.21,  7085.69,   100.08,  7265.24,  8210.55,
        3944.97,  3328.39,  1761.35,   659.6 , 11629.54])

In [48]:
# Lucro sem imposto de 30% (líquido)
lucro_liquido = lucro * 0.7
lucro_liquido

array([1337.973, 4404.547, 4959.983,   70.056, 5085.668, 5747.385,
       2761.479, 2329.873, 1232.945,  461.72 , 8140.678])

In [50]:
# Margem de lucro
margem = lucro_liquido / receitas
margem

array([0.17589956, 0.23665843, 0.25866373, 0.00799849, 0.62743886,
       0.49993433, 0.28276199, 0.22608449, 0.06708094, 0.04309514,
       0.52746804])

In [52]:
# Meses bons
lucro_medio = lucro_liquido.mean()
lucro_medio

3321.1188181818175

In [54]:
meses_bons = lucro_liquido > lucro_medio
meses_bons

array([False,  True,  True, False,  True,  True, False, False, False,
       False,  True])

In [55]:
# Retornar indices do vetor para meses bons
np.where(meses_bons)

(array([ 1,  2,  4,  5, 10]),)

In [56]:
# Retornar os valores de meses bons
lucro_liquido[meses_bons]

array([4404.547, 4959.983, 5085.668, 5747.385, 8140.678])

In [58]:
# Meses ruins
meses_ruins = np.where(meses_bons == False) # retornar os índices
meses_ruins

(array([0, 3, 6, 7, 8, 9]),)

In [61]:
# Melhor mês
lucro_liquido.max() # valor

8140.678

In [63]:
# índice
np.where(lucro_liquido == lucro_liquido.max())

(array([10]),)

In [64]:
# Pior mês
lucro_liquido.min()

70.05599999999994